language: python
python:
    - 3.7

sudo: required
        
branches:
    - master

addons:
    apt:
        packages:
            - doxygen
            - graphviz

install:
    - git clone https://github.com/Infineon/InfineonDoxyGenerator.git

script:
    - cd InfineonDoxyGenerator
    - python doxygen-ifx.py html

after_success:
    if: (branch = master) AND (tag IS present) 
        - python doxygen-ifx.py release $GH_USER $GH_PASS_TOKEN
