language: python
python:
    - 3.7

sudo: required
        
branches:
    - master
    - /^v.*$/

addons:
    apt:
        packages:
            - doxygen
            - graphviz
install: 
    git clone https://github.com/Infineon/InfineonDoxyGenerator.git

jobs:
  include:
    - stage: Compile 
      name: "Compilation"
      script: echo "Compiling ..."
    - stage: Test
      name: "Testing"
      script: 
        - echo "Testing ..."
        - git remote -v
    #     - echo "Testing more things..."
    # - script: echo "Something that can run in parallel in same stage ..."
    #   name: "Integration Testing"
    - stage: "Deploy" 
      if: tag IS present
      name: "GitHub Pages Deployment"
      script: 
        - cd InfineonDoxyGenerator
        - python doxygen-ifx.py html
        - python doxygen-ifx.py release $GH_USER $GH_PASS_TOKEN
    #   after_success:
    #     - python doxygen-ifx.py release $GH_USER $GH_PASS_TOKEN

