language: python
python:
    - 3.7

sudo: required
        
branches:
    - master
    - /^v.*$/

addons:
    apt:
        packages:
            - doxygen
            - graphviz
install: 
    - pip install -U platformio
    - platformio platform install -f infineonxmc 
    - platformio platform install -f atmelavr
    - git clone https://github.com/Infineon/InfineonDoxyGenerator.git

jobs:
  include:
    - stage: Compile 
      name: "Compilation"
      env:
        - matrix:
            - PLATFORMIO_CI_SRC=examples/exampleA
      script: 
            - platformio ci --lib="." --board=xmc1100_xmc2go --board=xmc1100_boot_kit --board=xmc4700_relax_kit --board=uno 
    - stage: Test
      name: "Testing"
      script: 
        - echo "Testing ..."
    #     - echo "Testing more things..."
    # - script: echo "Something that can run in parallel in same stage ..."
    #   name: "Integration Testing"
    - stage: "Deploy" 
      if: tag IS present
      name: "GitHub Pages Deployment"
      script: 
        - cd InfineonDoxyGenerator
        - python doxyifx.py html
        - python doxyifx.py release $GH_USER $GH_PASS_TOKEN
    #   after_success:
    #     - python doxygen-ifx.py release $GH_USER $GH_PASS_TOKEN

