language: python
python:
    - 3.7

sudo: required
        
branches:
    - master
    - /^v.*$/

addons:
    apt:
        # packages:
        #     - doxygen
        #     - graphviz
        sources:
            - ubuntu-toolchain-r-test
install: 
    # - pip install -U platformio
    # - platformio platform install -f infineonxmc 
    # - platformio platform install -f atmelavr
    # - git clone https://github.com/Infineon/InfineonDoxyGenerator.git
      - pip install cpp-coveralls

env:
    matrix:
        - PLATFORMIO_CI_SRC=examples/exampleA

jobs:
  include:
    # - stage: Compile 
    #   name: "Compilation"

    #   script: 
    #         - platformio ci --lib="." --board=xmc1100_xmc2go --board=xmc1100_boot_kit --board=xmc4700_relax_kit --board=uno 
    - stage: Test
      name: "Testing"
      script: 
        - git clone https://github.com/google/googletest.git
        - mkdir build && cd build
        - cmake ..
        - cmake --build . 
        - ctest
      after_success:
        coveralls --root .. -e test -e googletest -e docs -e InfineonDoxyGenerator -e build/CMakeFiles/3.15.2
         
         

    #     - echo "Testing more things..."
    # - script: echo "Something that can run in parallel in same stage ..."
    #   name: "Integration Testing"
    - stage: "Deploy" 
      if: tag IS present
      name: "GitHub Pages Deployment"
      script: 
        - cd InfineonDoxyGenerator
        - python doxyifx.py html
        - python doxyifx.py release $GH_USER $GH_PASS_TOKEN
    #   after_success:
    #     - python doxygen-ifx.py release $GH_USER $GH_PASS_TOKEN

