language: python
python:
    - 3.7

sudo: required
        
branches:
    - master

# stages:
#     - name: Compile
#     - name: Test
#     - name: Deploy
#         if: (branch = master) AND (tag IS present) 

# jobs:
#     include:
#         - stage: Compile
#             script: echo "Compiling something"
#         - stage: Test
#             script: echo "Running Test 1"   
#             script: echo "Running Test 2"
#         - stage: Deploy
#             script: echo "Deploying"

jobs:
  include:
    - stage: Compile 
      script: echo "Running unit tests (1)"
    - script: echo "Running unit tests (2)"
    - stage: GitHub Pages Deploy
      script: echo "Deploying to GitHub releases ..."


# addons:
#     apt:
#         packages:
#             - doxygen
#             - graphviz

install: skip
    # git clone https://github.com/Infineon/InfineonDoxyGenerator.git

script:
    - echo "Hello World!" 
    # - cd InfineonDoxyGenerator
    # - python doxygen-ifx.py html

# after_success:
#     if: (branch = master) AND (tag IS present) 
#         - python doxygen-ifx.py release $GH_USER $GH_PASS_TOKEN
