language: python
python:
    - 3.7

sudo: required
        
branches:
    - master
    - /^v.*$/

# stages:
#     - name: Compile
#     - name: Test
#     - name: Deploy
#         if: (branch = master) AND (tag IS present) 

# addons:
#     apt:
#         packages:
#             - doxygen
#             - graphviz

install: skip
    # git clone https://github.com/Infineon/InfineonDoxyGenerator.git

jobs:
  include:
    - stage: Compile 
      name: "Compilation"
      script: echo "Compiling ..."
    - stage: Test
      name: "Unit Testing"
      script: 
        - echo "Testing ..."
        - echo "Testing more things..."
    - script: echo "Something that can run in parallel in same stage ..."
      name: "Integration Testing"
    - stage: "Deploy" 
      if: tag IS present
      name: "GitHub Pages Deployment"
      script: 
        - echo "Generating Doxygen HTML documentation ..."
        # - cd InfineonDoxyGenerator
        # - python doxygen-ifx.py html
      after_success:
        - echo "sucess"
#         - python doxygen-ifx.py release $GH_USER $GH_PASS_TOKEN


# script:
#     - echo "Hello World!" 
    # - cd InfineonDoxyGenerator
    # - python doxygen-ifx.py html

# after_success:
#     if: (branch = master) AND (tag IS present) 

